### PR TITLE
PR: gh #100: Fixing direct leaks informed by sanitizer

### LINKED ISSUE #100: Bug: Based on the sanitizer report fix direct leaks
### Problem/Opportunity

Address sanitizer has pending 3 direct leaks that needs to be looked at.
https://github.com/user-attachments/files/22966907/SanitizerEnabled-TestLogs-Ut-control-tests.rtf

### Steps to reproduce

run ut-control tests
after quitting tests sanitizer logs are visible with both direct and indirect leaks

### Expected Behavior

Al direct leaks should be fixed.

### Actual Behavior

There are 3 direct leaks pending now.

### Notes (Optional)

_No response_

### LINKED ISSUE #101: Update the ut_control_keyStringMapping_t struct as getting build warning
update the ut_control_keyStringMapping_t 
from: typedef struct
      {
          char *string;
          int32_t value;
      } ut_control_keyStringMapping_t;
 
to: typedef struct
    {
        const char *string;
        int32_t value;
    } ut_control_keyStringMapping_t;

`/home/krt465/karthikeyan/Polaris_nonAV/hands-on/address_bhanu_RVC-3/rdk-halif-aidl-test-indicator/src/vts_indicator_helper_fu
nctions.cpp:68:6: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   68 |     {"false", (int32_t) false},
      |      ^~~~~~~
/home/krt465/karthikeyan/Polaris_nonAV/hands-on/address_bhanu_RVC-3/rdk-halif-aidl-test-indicator/src/vts_indicator_helper_fu
nctions.cpp:69:6: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   69 |     {"true",  (int32_t) true},
      |      ^~~~~~
/home/krt465/karthikeyan/Polaris_nonAV/hands-on/address_bhanu_RVC-3/rdk-halif-aidl-test-indicator/src/vts_indicator_helper_fu
nctions.cpp:75:6: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   75 |     {"EX_NONE",                  (int32_t) Status::EX_NONE},
      |      ^~~~~~~~~
/home/krt465/karthikeyan/Polaris_nonAV/hands-on/address_bhanu_RVC-3/rdk-halif-aidl-test-indicator/src/vts_indicator_helper_fu
nctions.cpp:76:6: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   76 |     {"EX_SECURITY",              (int32_t) Status::EX_SECURITY},`

### PR DESCRIPTION
**Pull request by kanjoe24**
This PR fixes direct leaks informed by sanitizer

### CODE REVIEW

**Comment by kanjoe24** [comment]
Attaching the test logs.
[Uploading fix_direct_leaks_review_comments-logs.rtf…]()

**Comment by kanjoe24** [comment]
Raised this ticket to fix indirect leaks: https://github.com/rdkcentral/ut-control/issues/103

File: src/ut_control_plane.c [hunk 1]
```diff
@@ -205,27 +205,45 @@ static void *service_state_machine(void *data)
...
-
+                UT_CONTROL_PLANE_ERROR("Unknown message type received: %d\n", msg->status);
+                if( msg)
+                {
+                    free(msg);
+                    msg = NULL;
+                }
             }
             break;
         }
```
Comment (Ulrond) [inline src/ut_control_plane.c:243]: you want may to consolidate the free logic outside of the switch, thus creating a focus point for doing the logic in all cases correctly? Which covers all cases, in a single point of failure?

**Review by Ulrond — DISMISSED** [review]
it;s good, but I wanted you to review this point if you feel it's worth tackling.

File: src/ut_control_plane.c (hunk 1 above)
Comment (kanjoe24) [reply src/ut_control_plane.c:243]: done

File: src/ut_control_plane.c [hunk 2]
```diff
@@ -219,25 +225,37 @@ static void *service_state_machine(void *data)
...
             default:
             {
-
+                UT_CONTROL_PLANE_ERROR("Unknown message type received: %d\n", msg->status);
+                break;
             }
-            break;
+        }
+
+        if (free_message_payload && msg->message != NULL)
```
Comment (Ulrond) [inline src/ut_control_plane.c]: don't think free_message_payload is required is it? happy to keep it, just asking if it's needed. is msg-> message ? not null always if here's no payload?

since msg-> mesasge != NULL is your check, and msg 


```c
    if (msg != NULL)
    {
        if (msg->message != NULL)
        {
            free(msg->message);
        }
        free(msg);
    }
```

Comment (kanjoe24) [reply src/ut_control_plane.c]: yes, this should also work..let me update and see.

Comment (kanjoe24) [reply src/ut_control_plane.c]: done

File: src/ut_control_plane.c [hunk 3]
```diff
@@ -329,26 +347,26 @@ static int callback_http(struct lws *wsi, enum lws_callback_reasons reason, void
...
-                enqueue_message(&msg, pInternal);
-                // char response[] = "{\"status\": \"success\"}";
-                // lws_write(wsi, (unsigned char *)response, strlen(response), LWS_WRITE_HTTP);
-                return 1; // HTTP request handled
+                UT_CONTROL_PLANE_ERROR("Malloc failed\n");
+                break;
             }
+
+            memcpy(msg.message, perSessionData->post_data, msg.size);
+            msg.message[msg.size] = '\0';
```
Comment (Ulrond) [inline src/ut_control_plane.c:363]: are you not truncating the message? potentially?

Comment (kanjoe24) [reply src/ut_control_plane.c:363]: no, I am null terminating it.

Comment (kanjoe24) [reply src/ut_control_plane.c:363]: we were doing same thing before as well:
                `msg.message[perSessionData->post_data_len] = '\0';`
https://github.com/rdkcentral/ut-control/pull/102/files#diff-c320244cfc74cda06758e827698fe9907a54057c6a18f766f55beea104eddcdeL345

**Comment by kanjoe24** [comment]
test logs:

```
2025-10-24-15:56:06, LOG   , ut_console.c,   661 :      Test Complete : 'kvp ssequence include support on malloc data'

Run Summary:    Type  Total    Ran Passed Failed Inactive
              suites     15     15    n/a      0        0
               tests     73     73     73      0        0
             asserts    413    413    413      0      n/a

Elapsed time =    3.735 seconds


***************** CUNIT CONSOLE - MAIN MENU ******************************
(R)un  (S)elect  (L)ist  (A)ctivate  (F)ailures  (O)ptions  (H)elp  (Q)uit
Enter command: q

2025-10-24-15:56:09, LOG   , ut_cunit.c,   177 : Logfile:[/tmp/ut-log_2025-10-24_155529.log]
2025-10-24-15:56:09, LOG   , ut_cunit.c,   185 : ---- end of test run ----

=================================================================
==2462012==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 4160 byte(s) in 20 object(s) allocated from:
    #0 0x7fb81d0ab887 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7fb81cebbc69 in fy_token_alloc_rl framework/linux/libfyaml-master/src/lib/fy-token.h:164
    #2 0x7fb81cebbc69 in fy_token_queue_simple_internal framework/linux/libfyaml-master/src/lib/fy-parse.c:189
    #3 0x7fb81cebbe1f in fy_token_queue_simple framework/linux/libfyaml-master/src/lib/fy-parse.c:215
    #4 0x7fb81cec59df in fy_fetch_stream_start framework/linux/libfyaml-master/src/lib/fy-parse.c:1800
    #5 0x7fb81ceebd8e in fy_fetch_tokens framework/linux/libfyaml-master/src/lib/fy-parse.c:4922
    #6 0x7fb81ceedf81 in fy_scan_peek framework/linux/libfyaml-master/src/lib/fy-parse.c:5236
    #7 0x7fb81ceefb46 in fy_parse_internal framework/linux/libfyaml-master/src/lib/fy-parse.c:5709
    #8 0x7fb81cef4115 in fy_parse_private framework/linux/libfyaml-master/src/lib/fy-parse.c:6666
    #9 0x7fb81cefb6c8 in fy_document_builder_load_document framework/linux/libfyaml-master/src/lib/fy-docbuilder.c:560
    #10 0x7fb81ce6d8ec in fy_parse_load_document_with_builder framework/linux/libfyaml-master/src/lib/fy-doc.c:1920
    #11 0x7fb81ce6d99c in fy_parse_load_document framework/linux/libfyaml-master/src/lib/fy-doc.c:1942
    #12 0x7fb81ce70ec5 in fy_document_build_internal framework/linux/libfyaml-master/src/lib/fy-doc.c:3285
    #13 0x7fb81ce7124f in fy_document_build_from_file framework/linux/libfyaml-master/src/lib/fy-doc.c:3363
    #14 0x7fb81cf166f6 in process_include src/ut_kvp.c:1148
    #15 0x7fb81cf16004 in process_node_copy src/ut_kvp.c:990
    #16 0x7fb81cf140b5 in ut_kvp_openMemory src/ut_kvp.c:209
    #17 0x558ab1bfd436 in create_delete_kvp_memory_instance_for_given_file /home/jpn323/workspace/ut-control/tests/src/ut_test_kvp.c:990
    #18 0x558ab1bfd678 in test_ut_kvp_singleIncludeFileWithBuildFromMallocedData /home/jpn323/workspace/ut-control/tests/src/ut_test_kvp.c:1027
    #19 0x558ab1c000ed in run_single_test /home/jpn323/workspace/ut-control/tests/ut-core/framework/CUnit-2.1-3/CUnit/Sources/Framework/TestRun.c:991
    #20 0x558ab1c00918 in run_single_suite /home/jpn323/workspace/ut-control/tests/ut-core/framework/CUnit-2.1-3/CUnit/Sources/Framework/TestRun.c:876

```

**Review by Ulrond — APPROVED** [review]
looks good

**Comment by kanjoe24** [comment]
Also raised : https://github.com/rdkcentral/ut-control/issues/103, to fix indirect leaks

**Comment by kanjoe24** [comment]
Release test logs:

```
./release-test-script-ut-control.sh -t feature/gh100-fix-direct-leaks
==========================================================
RESULTS for kirkstone_arm 
On the branch feature/gh100-fix-direct-leaks. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for ubuntu 
On the branch feature/gh100-fix-direct-leaks. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for VM-SYNC 
On the branch feature/gh100-fix-direct-leaks. PASS
build/linux/curl/lib/libcurl.a exists. PASS
build/linux/openssl/lib/libssl.a exists. PASS 
host-tools/CMake-3.30.0/build/bin/cmake exists. PASS 
==========================================================
==========================================================
RESULTS for dunfell_arm 
On the branch feature/gh100-fix-direct-leaks. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for dunfell_linux 
On the branch feature/gh100-fix-direct-leaks. PASS
CURL static lib does not exist. PASS
Openssl static lib does not exist. PASS 
CMake host binary exists. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_arm 
On the branch feature/gh100-fix-direct-leaks. PASS
build/arm/curl/lib/libcurl.a exists. PASS
build/arm/openssl/lib/libssl.a exists. PASS 
CMake host binary does not exist. PASS 
==========================================================
==========================================================
RESULTS for kirkstone_linux 
On the branch feature/gh100-fix-direct-leaks. PASS
build/linux/curl/lib/libcurl.a exists. PASS
Openssl static lib does not exist. PASS 
CMake host binary does not exist. PASS 
==========================================================

```
